from typing import Any, Dict, List

REQUIRED_TEMPLATE_KEYS: List[str] = [
    "cor_fundo",
    "cor_card",
    "cor_destaque",
    "cor_texto",
    "cor_preco",
    "cor_categoria",
    "cor_rodape",
    "cor_header_texto",
    "cor_info_fundo",
    "cor_info_texto",
    "cor_info_borda",
    "cor_promo_fundo",
    "cor_promo_texto",
    "cor_promo_badge",
    "cor_promo_badge_texto",
    "is_promocao",
]

# Paletas de fallback (o Node normalmente já envia o template resolvido em
# `template_customizado`, mas mantemos as mesmas 9 paletas aqui para permitir
# testes standalone do serviço e como referência).
TEMPLATES: Dict[str, Dict[str, Any]] = {
    "dark_red": {
        "cor_fundo": "#1a1a1a",
        "cor_card": "#2d2d2d",
        "cor_destaque": "#c0392b",
        "cor_texto": "#f5f5f5",
        "cor_preco": "#e74c3c",
        "cor_categoria": "#e74c3c",
        "cor_rodape": "#c0392b",
        "cor_header_texto": "#ffffff",
        "cor_info_fundo": "#2d2d2d",
        "cor_info_texto": "#f5f5f5",
        "cor_info_borda": "#c0392b",
        "cor_promo_fundo": "#c0392b",
        "cor_promo_texto": "#ffffff",
        "cor_promo_badge": "#f1c40f",
        "cor_promo_badge_texto": "#1a1a1a",
        "is_promocao": False,
    },
    "light_fresh": {
        "cor_fundo": "#f7f9f7",
        "cor_card": "#ffffff",
        "cor_destaque": "#27ae60",
        "cor_texto": "#2c3e50",
        "cor_preco": "#27ae60",
        "cor_categoria": "#27ae60",
        "cor_rodape": "#27ae60",
        "cor_header_texto": "#ffffff",
        "cor_info_fundo": "#eafaf1",
        "cor_info_texto": "#2c3e50",
        "cor_info_borda": "#27ae60",
        "cor_promo_fundo": "#27ae60",
        "cor_promo_texto": "#ffffff",
        "cor_promo_badge": "#f39c12",
        "cor_promo_badge_texto": "#ffffff",
        "is_promocao": False,
    },
    "elegante": {
        "cor_fundo": "#0d0d0d",
        "cor_card": "#1f1f1f",
        "cor_destaque": "#0d0d0d",
        "cor_texto": "#f0e6d2",
        "cor_preco": "#d4af37",
        "cor_categoria": "#d4af37",
        "cor_rodape": "#0d0d0d",
        "cor_header_texto": "#d4af37",
        "cor_info_fundo": "#1f1f1f",
        "cor_info_texto": "#f0e6d2",
        "cor_info_borda": "#d4af37",
        "cor_promo_fundo": "#d4af37",
        "cor_promo_texto": "#0d0d0d",
        "cor_promo_badge": "#c9a227",
        "cor_promo_badge_texto": "#0d0d0d",
        "is_promocao": False,
    },
    "tropical": {
        "cor_fundo": "#fff8e1",
        "cor_card": "#ffffff",
        "cor_destaque": "#ff7043",
        "cor_texto": "#4e342e",
        "cor_preco": "#ff7043",
        "cor_categoria": "#f9a825",
        "cor_rodape": "#00897b",
        "cor_header_texto": "#ffffff",
        "cor_info_fundo": "#fff3e0",
        "cor_info_texto": "#4e342e",
        "cor_info_borda": "#ff7043",
        "cor_promo_fundo": "#ff7043",
        "cor_promo_texto": "#ffffff",
        "cor_promo_badge": "#fdd835",
        "cor_promo_badge_texto": "#4e342e",
        "is_promocao": False,
    },
    "noite_azul": {
        "cor_fundo": "#0f1626",
        "cor_card": "#1c2740",
        "cor_destaque": "#2e86de",
        "cor_texto": "#e8edf5",
        "cor_preco": "#54a0ff",
        "cor_categoria": "#54a0ff",
        "cor_rodape": "#0f1626",
        "cor_header_texto": "#ffffff",
        "cor_info_fundo": "#1c2740",
        "cor_info_texto": "#e8edf5",
        "cor_info_borda": "#2e86de",
        "cor_promo_fundo": "#2e86de",
        "cor_promo_texto": "#ffffff",
        "cor_promo_badge": "#f1c40f",
        "cor_promo_badge_texto": "#0f1626",
        "is_promocao": False,
    },
    "promo_fogo": {
        "cor_fundo": "#1a0a05",
        "cor_card": "#2b1108",
        "cor_destaque": "#ff4500",
        "cor_texto": "#fff5e6",
        "cor_preco": "#ffeb3b",
        "cor_categoria": "#ff7043",
        "cor_rodape": "#ff4500",
        "cor_header_texto": "#ffffff",
        "cor_info_fundo": "#2b1108",
        "cor_info_texto": "#fff5e6",
        "cor_info_borda": "#ff4500",
        "cor_promo_fundo": "#ff4500",
        "cor_promo_texto": "#ffffff",
        "cor_promo_badge": "#ffeb3b",
        "cor_promo_badge_texto": "#1a0a05",
        "is_promocao": True,
    },
    "promo_black": {
        "cor_fundo": "#000000",
        "cor_card": "#1a1a1a",
        "cor_destaque": "#000000",
        "cor_texto": "#ffffff",
        "cor_preco": "#ffd700",
        "cor_categoria": "#ffd700",
        "cor_rodape": "#000000",
        "cor_header_texto": "#ffd700",
        "cor_info_fundo": "#1a1a1a",
        "cor_info_texto": "#ffffff",
        "cor_info_borda": "#ffd700",
        "cor_promo_fundo": "#ffd700",
        "cor_promo_texto": "#000000",
        "cor_promo_badge": "#ff0000",
        "cor_promo_badge_texto": "#ffffff",
        "is_promocao": True,
    },
    "promo_verao": {
        "cor_fundo": "#e0f7fa",
        "cor_card": "#ffffff",
        "cor_destaque": "#00acc1",
        "cor_texto": "#01579b",
        "cor_preco": "#ff9800",
        "cor_categoria": "#00acc1",
        "cor_rodape": "#00acc1",
        "cor_header_texto": "#ffffff",
        "cor_info_fundo": "#fff8e1",
        "cor_info_texto": "#01579b",
        "cor_info_borda": "#00acc1",
        "cor_promo_fundo": "#ff9800",
        "cor_promo_texto": "#ffffff",
        "cor_promo_badge": "#ffeb3b",
        "cor_promo_badge_texto": "#01579b",
        "is_promocao": True,
    },
    "promo_natal": {
        "cor_fundo": "#0b2e13",
        "cor_card": "#14401d",
        "cor_destaque": "#c0392b",
        "cor_texto": "#fdf6e3",
        "cor_preco": "#ffd700",
        "cor_categoria": "#ffd700",
        "cor_rodape": "#c0392b",
        "cor_header_texto": "#ffd700",
        "cor_info_fundo": "#14401d",
        "cor_info_texto": "#fdf6e3",
        "cor_info_borda": "#ffd700",
        "cor_promo_fundo": "#c0392b",
        "cor_promo_texto": "#fdf6e3",
        "cor_promo_badge": "#ffd700",
        "cor_promo_badge_texto": "#0b2e13",
        "is_promocao": True,
    },
}


def validate_template(template: Dict[str, Any]) -> List[str]:
    """Retorna a lista de chaves obrigatórias que estão faltando (vazia = válido)."""
    if not isinstance(template, dict):
        return list(REQUIRED_TEMPLATE_KEYS)
    return [key for key in REQUIRED_TEMPLATE_KEYS if key not in template]


def resolve_template(template_key: str | None, template_customizado: Dict[str, Any] | None) -> Dict[str, Any]:
    if template_customizado:
        faltando = validate_template(template_customizado)
        if faltando:
            raise ValueError(f"template_customizado inválido, faltando: {', '.join(faltando)}")
        return template_customizado
    if template_key and template_key in TEMPLATES:
        return TEMPLATES[template_key]
    raise ValueError("Informe 'template_key' válido ou 'template_customizado'.")
